name = "correo-solid"
compatibility_date = "2024-06-01"


[vars]
API_KEY = "123456"
SENDER_EMAIL = "onboarding@resend.dev"


[[d1_databases]]
binding = "DB"  
database_name = "correos"
database_id = "f0dfbec2-8b93-4e06-b7a7-8c898916f445"  

[[d1_databases]]
binding = "EMAIL_TRACKING"
database_name = "email-tracking-db"
database_id = "a7644d6b-4ab2-406c-a069-405c201af1b3"


[build]
command = "pnpm run build"
upload_dir = "dist"